# startup_input: "!"
stages:
  - db:
      port: 5432
      password: postgres
      data_dir: ~/.postgres

  - master:
      pre:
        - sh: make -C master build
        - sh: make -C tools prep-root
      post:
        - conncheck:
            port: 8080
      config_file:
        db:
          host: localhost
          port: 5432
          password: postgres
          user: postgres
          name: determined
        checkpoint_storage:
          type: shared_fs
          host_path: /tmp
          storage_path: determined-cp
        log:
          level: debug
        root: tools/build

  - agent:
      pre:
        - sh: make -C agent build
      config_file:
        master_host: 127.0.0.1
        master_port: 8080
        container_master_host: $DOCKER_LOCALHOST
